apiVersion: v1
kind: ConfigMap
metadata:
  name: iotedge-spiffe-agent
data:
  Config.toml: |
    socket_path = "{{ .Values.socket.path }}{{ .Values.socket.workload }}"
    trust_domain = "iotedge"

    [server-config]
    address = "iotedge-spiffe-server"
    port = 8443

    [trust-bundle-config]
    max_retry = 3
    wait_retry_sec = 3

    [node_attestation_config]
    type = "PSAT"
    [node_attestation_config.content]
    token_path = "/var/run/secrets/tokens/iotedge-spiffe-agent"

    [workload_attestation_config]
    type = "K8S"
    [workload_attestation_config.content]
