apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: iotedge-spiffe-agent
  labels:
    app: iotedge-spiffe-agent
spec:
  selector:
    matchLabels:
      app: iotedge-spiffe-agent
  template:
    metadata:
      labels:
        app: iotedge-spiffe-agent
    spec:
      hostPID: true
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet    
      serviceAccountName: iotedge-spiffe-agent
      initContainers:
        - name: init-server
          # This is a small image with wait-for-it, choose whatever image
          # you prefer that waits for a service to be up. This image is built
          # from https://github.com/lqhl/wait-for-it
          image: gcr.io/spiffe-io/wait-for-it
          args: ["-t", "30", "iotedge-spiffe-server:8443"]
      containers:
        - name: iotedge-spiffe-agent
          image: "{{ .Values.agent.image.repository }}:{{ .Values.agent.image.tag }}"
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: config
              mountPath: /mnt/config
            - name: iotedge-spiffe-token
              mountPath: /var/run/secrets/tokens
            - name: iotedge-spiffe-agent-socket
              mountPath: {{ .Values.socket.path }}
      volumes:
        - name: config
          configMap:
            name: iotedge-spiffe-agent 
        - name: iotedge-spiffe-agent-socket
          hostPath:
            path: {{ .Values.socket.path }}
            type: DirectoryOrCreate            
        - name: iotedge-spiffe-token
          projected:
            sources:
            - serviceAccountToken:
                path: iotedge-spiffe-agent
                expirationSeconds: 7200
                audience: iotedge-spiffe-server
