apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: iotedge-spiffe-agent
  labels:
    app: iotedge-spiffe-agent
spec:
  selector:
    matchLabels:
      app: iotedge-spiffe-agent
  template:
    metadata:
      labels:
        app: iotedge-spiffe-agent
    spec:
      hostPID: true
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet    
      serviceAccountName: iotedge-spiffe-agent
      containers:
        - name: iotedge-spiffe-agent
          image: "{{ .Values.spiffe.agent.image.repository }}:{{ .Values.spiffe.agent.image.tag }}"
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: config
              mountPath: /mnt/config
            - name: iotedge-spiffe-token
              mountPath: /var/run/secrets/tokens
            - name: iotedge-spiffe-agent-socket
              mountPath: {{ .Values.spiffe.socket.path }}
      volumes:
        - name: config
          configMap:
            name: iotedge-spiffe-agent 
        - name: iotedge-spiffe-agent-socket
          hostPath:
            path: {{ .Values.spiffe.socket.path }}
            type: DirectoryOrCreate            
        - name: iotedge-spiffe-token
          projected:
            sources:
            - serviceAccountToken:
                path: iotedge-spiffe-agent
                expirationSeconds: 7200
                audience: iotedge-spiffe-server
