apiVersion: v1
kind: Service
metadata:
  name: mqttbroker
spec:
  ports:
    - name: mqtt
      port: 1883
      targetPort: 1883
      protocol: TCP
  selector:
    app: mqttbroker
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqttbroker
  labels:
    app: mqttbroker
spec:
  selector:
    matchLabels:
      app: mqttbroker
  template:
    metadata:
      labels:
        app: mqttbroker
    spec:
      containers:
        - name: mqttbroker
          image: "{{ .Values.mqtt.image.repository }}:{{ .Values.mqtt.image.tag }}"
          ports:
            - containerPort: 1883
          volumeMounts:
            - name: iotedge-spiffe-agent-socket
              mountPath: {{ .Values.spiffe.socket.path }}
      initContainers:
        - name: spiffe-workload-socket
          image: dmqttdemo.azurecr.io/single-broker-spiffe-init:latest
          env:
          - name: SPIFFE_ENABLED
            value: {{ .Values.mqtt.spiffe-enabled | quote }}
          volumeMounts:
            - name: iotedge-spiffe-agent-socket
              mountPath: {{ .Values.spiffe.socket.path }}
      volumes:
        - name: iotedge-spiffe-agent-socket
          hostPath:
            path: {{ .Values.spiffe.socket.path }}
            type: DirectoryOrCreate
