# Entries - These are the identities the mqtt broker will work with since it talks to identity manager
[[entry]]
spiffe_id = "1"
spiffe_id_path = "agent"
[entry.attestation_config]
type = "NODE"
[entry.attestation_config.content]
value = ["AGENTSERVICEACCOUNT:iotedge-spiffe-agent"]
plugin = "PSAT"

[[entry]]
spiffe_id = "2"
spiffe_id_path = "publisher"
[entry.attestation_config]
type = "WORKLOAD"
[entry.attestation_config.content]
value = ["PODLABELS:app:publisher"]
plugin = "K8S"
parent_id = "1"

[[entry]]
spiffe_id = "3"
spiffe_id_path = "mqttbroker"
[entry.attestation_config]
type = "WORKLOAD"
[entry.attestation_config.content]
value = ["PODLABELS:app:mqttbroker"]
plugin = "K8S"
parent_id = "1"

[[entry]]
spiffe_id = "4"
spiffe_id_path = "subscriber"
[entry.attestation_config]
type = "WORKLOAD"
[entry.attestation_config.content]
value = ["PODLABELS:app:subscriber"]
plugin = "K8S"
parent_id = "1"

[[entry]]
spiffe_id = "5"
spiffe_id_path = "bulkpublisher"
[entry.attestation_config]
type = "WORKLOAD"
[entry.attestation_config.content]
value = ["PODLABELS:app:bulkpublisher"]
plugin = "K8S"
parent_id = "1"