name: "charts"

on: [workflow_dispatch]

env:
  HELM_EXPERIMENTAL_OCI: 1
  HELM_VERSION_TO_INSTALL: 3.8.0-linux-amd64.zip
  CHART_ACR_REPO_NAME: helm
  
jobs:
  build:
    name: Publish acr
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v2
        name: checkout repo
      
      - name: Install helm
        uses: Azure/setup-helm@v1
        with:
          version: ${{ env.HELM_VERSION_TO_INSTALL }}# default is latest
          
      - name: Login to Acr using Helm
        run: |
          echo ${{ secrets.ACR_CHART_PASSWORD }} | helm registry login ${{ secrets.ACR_CHART_REGISTRY }}.azurecr.io --username ${{ secrets.ACR_CHART_USERNAME }} --password-stdin 

      - name: Package E4K helm chart locally
        working-directory: charts/E4K
        run: |
          helm package .
      
      - name: Publish E4K chart to Acr
        working-directory: charts/E4K
        run: |
          helm push az-e4k-*.tgz  oci://${{ secrets.ACR_CHART_REGISTRY }}.azurecr.io/${{ env.CHART_ACR_REPO_NAME }}/

      - name: Package spiffe helm chart locally
        working-directory: charts/E4K/charts/e4kspiffe
        run: |
          helm package .
      
      - name: Publish spiffe chart to Acr
        working-directory: charts/E4K/charts/e4kspiffe
        run: |
          helm push e4kspiffe-*.tgz  oci://${{ secrets.ACR_CHART_REGISTRY }}.azurecr.io/${{ env.CHART_ACR_REPO_NAME }}/

      - name: Package single node mqtt helm chart locally
        working-directory: charts/E4K/charts/e4kmqtt
        run: |
          helm package .
      
      - name: Publish single node mqtt chart to Acr
        working-directory: charts/E4K/charts/e4kmqtt
        run: |
          helm push e4kmqtt-*.tgz  oci://${{ secrets.ACR_CHART_REGISTRY }}.azurecr.io/${{ env.CHART_ACR_REPO_NAME }}/
