name: "charts"

on: [workflow_dispatch]

env:
  HELM_EXPERIMENTAL_OCI: 1
  HELM_VERSION_TO_INSTALL: 3.8.0-linux-amd64.zip
  ACR_REPO_NAME: helm
  
jobs:
  build:
    name: Publish acr
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v2
        name: checkout repo
      
      - name: install helm
        uses: Azure/setup-helm@v1
        with:
          version: ${{ env.HELM_VERSION_TO_INSTALL }}# default is latest
          
      - name: login to acr using helm
        run: |
          echo ${{ secrets.ACR_CHART_PASSWORD }} | helm registry login ${{ secrets.ACR_CHART_REGISTRY }}.azurecr.io --username ${{ secrets.ACR_CHART_USERNAME }} --password-stdin 
          
      - name: save helm chart to local registry
        working-directory: charts/iotedge-spiffe
        run: |
          helm package .
      
      - name: publish chart to acr
        working-directory: charts/iotedge-spiffe
        run: |
          helm push edge-spiffe-*.tgz  oci://${{ secrets.ACR_CHART_REGISTRY }}.azurecr.io/${{ env.ACR_REPO_NAME }}/
