name: "charts"

on: 
  workflow_dispatch:
    inputs:
      chartVersion:
        description: 'The Chart version to package/push with'     
        required: true
        default: 'latest'

env:
  HELM_EXPERIMENTAL_OCI: 1
  HELM_VERSION_TO_INSTALL: 3.6.3-linux-amd64.zip
  ACR_REPO_NAME: helm/spiffe
  
jobs:
  build:
    name: Publish acr
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v2
        name: checkout repo
      
      - name: install helm
        uses: Azure/setup-helm@v1
        with:
          version: ${{ env.HELM_VERSION_TO_INSTALL }}# default is latest
          
      - name: login to acr using helm
        run: |
          echo ${{ secrets.ACR_CHART_PASSWORD }} | helm registry login ${{ secrets.ACR_CHART_REGISTRY }}.azurecr.io --username ${{ secrets.ACR_CHART_USERNAME }} --password-stdin 
          
      - name: save helm chart to local registry
        run: |
          helm chart save ${{ secrets.ACR_CHART_REGISTRY }}/charts/iotedge-spiffe/ ${{ secrets.ACR_CHART_REGISTRY }}.azurecr.io/helm/spiffe:${{ github.event.inputs.chartVersion }}
      
      - name: publish chart to acr
        run: |
          helm chart push ${{ secrets.ACR_CHART_REGISTRY }}.azurecr.io/helm/spiffe:${{ github.event.inputs.chartVersion }}
